### ISSUE TITLE
Where are the maps？

### ISSUE THREAD

**Issue by YYan99** [flying-cabbage/drift_drl#2]
I download the simulator,but can't find the maps.Would you share it with us? Thank you

**Comment by caipeide** [comment]
The maps are already in the simulator, you can download it from  [from this link](https://drive.google.com/drive/folders/1JBwUr5OzbemR3XDu9tG0BEFJEHQ-vp_Z?usp=sharing).
1. To load map(a) for the first-stage training, run:
`./CarlaUE4.sh /Game/Carla/ExportedMaps/simple`
2. To load map(b-f) for the second-stage training, run:
`./CarlaUE4.sh /Game/Carla/ExportedMaps/train`
3. To load test map(g) for evaluation, run:
`./CarlaUE4.sh /Game/Carla/ExportedMaps/test_refined`

**Comment by YYan99** [comment]
Thank you for your reply! It works
